project_id: "427504"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
preserve_hierarchy: true

files:
  - source: "src/main/generated/assets/artisanat/lang/en_us.json"
    translation: "src/main/generated/assets/artisanat/lang/%locale_with_underscore%.json"
    dest: "artisanat.json"
  - source: "docs/**/*.*"
    ignore:
      - "docs/.assets/**/*"
      - "docs/.translated/**/*"
      - "docs/sinytra-wiki.json"
    translation: "docs/.translated/%locale_with_underscore%/**/%original_file_name%"
    dest: "artisanat-docs/**/%original_file_name%"