org.gradle.jvmargs=-Xmx1G

# Mod Metadata
mod_id=artisanat
mod_name=Artisanat
mod_logo=https://raw.githubusercontent.com/DawnTeamMC/Artisanat/refs/heads/main/images/icon.png
mod_color=2136530

loader_name=Fabric
loader_icon=https://fabricmc.net/assets/logo.png

# check these on https://fabricmc.net/versions.html
minecraft_version=26.1
loader_version=0.18.6
loom_version=1.16-SNAPSHOT

# Fabric API
fabric_api_version=0.145.1+26.1