package fr.hugman.artisanat.neoforge;

import fr.hugman.artisanat.Artisanat;
import fr.hugman.artisanat.platform.ArtisanatPlatform;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.common.Mod;
import net.neoforged.neoforge.registries.RegisterEvent;

@Mod(Artisanat.MOD_ID)
public class ArtisanatNeoForge {
    private static boolean registered = false;

    public ArtisanatNeoForge(IEventBus modBus) {
        ((ArtisanatNeoForgePlatform) ArtisanatPlatform.INSTANCE).subscribe(modBus);
        modBus.addListener(RegisterEvent.class, ArtisanatNeoForge::register);
    }

    /**
     * NeoForge keeps every registry open for the whole registration phase, so everything is registered at once, like on Fabric.
     * Oxidation and waxing come from the {@code neoforge:oxidizables} and {@code neoforge:waxables} data maps, generated by Fabric datagen.
     */
    private static void register(RegisterEvent event) {
        if (registered) return;
        registered = true;
        Artisanat.init();
    }
}
